image: alpine:latest

stages:
  - build
  - deploy

## all branchs can build html
build:
  image: timbru31/node-alpine-git:12
  tags: [pages]
  stage: build
  before_script:
    - yarn install --ignore-scripts --registry https://registry.npm.taobao.org 
  script:
    - yarn build
  cache:
    key: docusaurus-2.0.0-alpha.69 # caching by docusaurus version.
    paths:
    - node_modules/
  artifacts:
    paths:
    - build

pages:
  tags: [pages]
  stage: deploy
  script:
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
